[build]
  command = "npm run build"
  publish = "dist/stoq-front/browser"
[build.environment]
  NETLIFY_SKIP_PLUGIN_INSTALL = "true"

  [[plugins]]
package = "@netlify/angular-runtime"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200